name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set release tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      
      - name: Set up zip (excluding unwanted files)
        run: |
          rm -rf .git .github README.md assets/demo.gif assets/easy_version.png assets/premium_paywall.png
          zip -r Tab3U-${{ env.RELEASE_TAG  }}.zip .
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG  }}
          name: Release ${{ env.RELEASE_TAG  }}
          files: Tab3U-${{ env.RELEASE_TAG  }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}